config/routes.rb
Rails.application.routes.draw do
  get 'tops/index'

  resources :events do
    collection do
      post :confirm
    end
  end
  root 'tops#index'
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :participant_managements, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/inbox"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, :date, :place, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 255 }

  belongs_to :user
  has_many :participant_managements, dependent: :destroy
  has_many :participant_management_users, through: :participant_managements, source: :user
end

app/models/participant_management.rb
class ParticipantManagement < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :events
  has_many :participant_managements, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :user_logged_in, only: [:new, :show, :edit, :update, :destroy]

  def new
    @event = Event.new
    if params[:back]
      @event = Event.new(event_params)
    else
      @event = Event.new
    end
  end

  def confirm
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    render :new if @event.invalid?
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to new_event_path, notice: "イベントを作成しました！"
    else
      render "new"
    end
  end

  def index
    @events = Event.page(params[:page]).per(3)
  end

  def show
    @participant_management = current_user.participant_managements.find_by(event_id: @event.id)
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to event_path, notice: "イベントを編集しました"
    else
      render "edit"
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice:"イベントを削除しました"
  end

  private
   def event_params
     params.require(:event).permit(:title, :date, :place, :content)
   end

   def set_event
     @event = Event.find(params[:id])
   end

   def user_logged_in
     unless logged_in?
       redirect_to new_session_path
     end
   end
end

app/controllers/participant_managements_controller.rb
class ParticipantManagementsController < ApplicationController
  def create
    participant = current_user.participant_managements.create(event_id: params[:event_id])
    redirect_to events_url, notice: "#{participant.event.user.name}さんのイベントに参加しました"
    ParticipantManagementMailer.participant_management_mail(participant).deliver
  end

  def destroy
    participant = current_user.participant_managements.find_by(event_id: params[:id]).destroy
    redirect_to events_url, notice: "#{participant.event.user.name}さんのイベントをキャンセルしました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました"
      render "new"
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
   params.require(:user).permit(:name, :email, :password, :password_confirmation)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "confirm"
      confirm_events_path
    elsif action_name == "edit"
      event_path
    end
  end
end

app/helpers/participant_managements_helper.rb
module ParticipantManagementsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: @event, local: true, url: choose_new_or_edit) do |form| %>
<% if @event.errors.any? %>
  <div id="error_explanation">
    <h2><%= @event.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="event_title">
  <%= form.label :イベント名 %>
  <%= form.text_field :title %>
</div>
<div class="event_title">
  <%= form.label :日時 %>
  <%= form.text_field :date %>
</div>
<div class="event_title">
  <%= form.label :場所 %>
  <%= form.text_field :place %>
</div>
<div class="event_title">
  <%= form.label :イベント内容 %>
  <%= form.text_field :content %>
</div>
<%= form.submit %>
<% end %>

app/views/events/confirm.html.erb
<h3>以下の内容で登録する。</h3>
<%= form_with(model: @event, url: events_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :date %>
  <%= form.hidden_field :place %>
  <%= form.hidden_field :content %>
  <p>イベント名:<%= @event.title %></p>
  <p>日時:<%= @event.date%></p>
  <p>場所:<%= @event.place%></p>
  <p>イベント内容:<%= @event.content %></p>
  <%= form.submit "登録する" %>
<% end %>

<%= form_with(model: @event, url: new_event_path, local: true, method: "get") do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :date %>
  <%= form.hidden_field :place %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/events/edit.html.erb
<h2>イベントを編集する</h2>
<%= render "form" %>

app/views/events/index.html.erb
<div class="container">
  <table class="table">
    <h1>イベント一覧</h1>
    <p><%= notice %></p>
    <thead>
      <tr>
        <th>イベント名</th>
        <th>イベント内容</th>
      </tr>
    </thead>
    <% @events.each do |event| %>
    <tbody>
      <tr>
        <td><%= event.title.truncate(10) %></td>
        <td><%= event.content.truncate(30) %></td>
        <td><%= link_to "イベントの詳細を確認する", event_path(event.id) %></td>
        <% if logged_in? && event.user_id == current_user.id %>
            <td><%= link_to "イベントを編集する", edit_event_path(event.id) %></td>
            <td><%= link_to "イベントを削除する", event_path(event.id), method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
          <% end %>
      </tr>
    </tbody>
    <% end %>
  </table>
  <%= paginate @events %>
  <br>
  <button type="button" class="btn btn-warning btn-lg"><%= link_to "新しくイベントを作成する", new_event_path %></button>
</div>

app/views/events/new.html.erb
<h2>イベントを作成する</h2>
<%= render "form" %>

app/views/events/show.html.erb
<h1>イベント詳細</h1>
<p><%= notice %></p>
<p>イベント名:<%= @event.title %></p>
<p>日時:<%= @event.date %></p>
<p>場所:<%= @event.place %></p>
<p>イベント内容:<%= @event.content %></p>

<% unless @event.user == current_user %>
  <% if @participant_management.present? %>
    <%= link_to "イベント参加をキャンセルする", participant_management_path(id: @event.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'イベントに参加する', participant_managements_path(event_id: @event.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventapp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">Bootstrap</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
          <% end %>
          <ul class="nav navbar-nav">
            <li><%= link_to "Eventapp", tops_index_path %></li>
            <% if logged_in? %>
              <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
              <li><%= link_to "イベントを作成する", new_event_path %></li>
              <li><%= link_to "イベント一覧", events_path %></li>
              <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
            <% else %>
              <li><%= link_to "新規ユーザー登録", new_user_path %></li>
              <li><%= link_to "ログイン", new_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/tops/index.html.erb
<h1>Eventapp</h1>
<p>スキルアップできるIT勉強会・イベント情報を提供しています。</p>
<%= image_tag "top.jpg" %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>
<% if @user.errors.any? %>
  <div id="error_explantion">
    <h2><%= pluralize(@user.errors.count, "エラー") %> prohibited this @user form being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "登録する" %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <header class="header">
    <h1><%= @user.name %>のページ</h1>
    <p>メールアドレス: <%= @user.email %></p>
  </header>
  <nav class="menu">
    <ul class="row">
      <li class="col-md-6">参加イベント一覧<br>
        <% @user.participant_managements.each do |participation| %>
          <%= participation.event.title %><br>
        <% end %>
      </li>
      <li class="col-md-6">企画イベント一覧<br>
        <% @user.events.each do |plan| %>
          <%= plan.title %><br>
        <% end %>
      </li>
    </ul>
  </nav>
</div>